### ISSUE TITLE
如果用bat執行，會出現錯誤訊息

### ISSUE THREAD

**Issue by pulipulichen** [pulipulichen/PrefixSpan-py#2]
````
Traceback (most recent call last):
  File "prefixspan.py", line 125, in <module>
    minvalue=10, maxvalue=1000, initialvalue=1000)
  File "D:\Program Files\Python27\lib\lib-tk\tkSimpleDialog.py", line 262, in as
kinteger
    d = _QueryInteger(title, prompt, **kw)
  File "D:\Program Files\Python27\lib\lib-tk\tkSimpleDialog.py", line 189, in __
init__
    Dialog.__init__(self, parent, title)
  File "D:\Program Files\Python27\lib\lib-tk\tkSimpleDialog.py", line 53, in __i
nit__
    if parent.winfo_viewable():
AttributeError: 'NoneType' object has no attribute 'winfo_viewable'
````

但是用python-caller.exe可以執行
我覺得這可能是我的問題

**Comment by pulipulichen** [comment]
我暫時不處理這個問題

如果那天我還需要用PrefixSpan，我會用其他程式語言來撰寫
此專案廢棄
